[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/filetracker"
healthcheckTimeout = 100

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
DB_CONNECTION = "mysql"
DB_HOST = "${{RAILWAY_PRIVATE_SERVICE_MYSQL_HOST}}"
DB_PORT = "${{RAILWAY_PRIVATE_SERVICE_MYSQL_PORT}}"
DB_DATABASE = "${{RAILWAY_PRIVATE_SERVICE_MYSQL_DATABASE}}"
DB_USERNAME = "${{RAILWAY_PRIVATE_SERVICE_MYSQL_USER}}"
DB_PASSWORD = "${{RAILWAY_PRIVATE_SERVICE_MYSQL_PASSWORD}}"
CACHE_DRIVER = "redis"
SESSION_DRIVER = "redis"
QUEUE_CONNECTION = "redis"
REDIS_HOST = "${{RAILWAY_PRIVATE_SERVICE_REDIS_HOST}}"
REDIS_PORT = "${{RAILWAY_PRIVATE_SERVICE_REDIS_PORT}}"
